apiVersion: v1
kind: ConfigMap
metadata:
  name: saas-platform-config
  namespace: artis
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  APP_PUBLIC_URL: "http://saas-platform:8081"
  FRONTEND_URL: "http://angular-platform:80"
  KEYCLOAK_URL: "http://keycloak:8080"
  PAYMEE_API_TOKEN: "c531dc47e04ad09ef573e87c08e4069323eee679"