server.port=8081

spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.flyway.enabled=false

provisioning.max-attempts=5
provisioning.retry-delay-ms=60000

app.frontend.client-id=artis-frontend

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=islemjridi19@gmail.com
spring.mail.password=eyap ggou vpnq xicr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

keycloak.server-url=http://localhost:8080
keycloak.admin-realm=master
keycloak.client-id=admin-cli
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:}