# ================= PROD =================

# PLATFORM DB
spring.datasource.url=jdbc:postgresql://postgres:5432/tenantdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ARTIS DB
artis.datasource.url=jdbc:postgresql://postgres:5432/artisdb
artis.datasource.username=${DB_USERNAME}
artis.datasource.password=${DB_PASSWORD}

# Keycloak
keycloak.server-url=${KEYCLOAK_URL}
keycloak.admin-realm=master
keycloak.client-id=${KEYCLOAK_CLIENT_ID}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

# Paymee PROD
paymee.api-key=${PAYMEE_API_KEY}
paymee.api-token=${PAYMEE_API_TOKEN}
paymee.base-url=https://app.paymee.tn/api/v2

paymee.public-base-url=${APP_PUBLIC_URL}
paymee.return-url-success=${APP_PUBLIC_URL}/api/payment/redirect-success
paymee.return-url-fail=${APP_PUBLIC_URL}/api/payment/redirect-cancel
paymee.webhook-url=${APP_PUBLIC_URL}/api/payment/webhook

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379

# Frontend
app.frontend.url=${FRONTEND_URL}