# DATABASE
spring.datasource.url=jdbc:postgresql://postgresql:5432/saasPlatform
spring.datasource.username=postgres
spring.datasource.password=postgres

# ARTIS DB
artis.datasource.url=jdbc:postgresql://postgresql:5432/artisdb
artis.datasource.username=postgres
artis.datasource.password=postgres
artis.datasource.driver-class-name=org.postgresql.Driver

# DEMO DB
demo.datasource.url=jdbc:postgresql://postgresql:5432/artisdb_demo
demo.datasource.username=postgres
demo.datasource.password=postgres
demo.datasource.driver-class-name=org.postgresql.Driver

# APP DATASOURCE DEMO
app.datasource.demo.url=jdbc:postgresql://postgresql:5432/artisdb_demo
app.datasource.demo.username=postgres
app.datasource.demo.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.enabled=false

# KEYCLOAK
app.keycloak.url=http://keycloak:8080
keycloak.server-url=http://keycloak:8080
keycloak.admin-realm=master
keycloak.client-id=admin-cli
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:}
keycloak.admin.username=admin
keycloak.admin.password=admin

# RABBITMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# URLS
#app.platform.url=http://saas-platform:8081
app.frontend.url=http://localhost:4200
app.metier.url=http://angular-metier:80

# CORS
app.cors.allowed-origins=http://angular-platform:80,http://angular-metier:80,http://localhost:4200,http://localhost:4201

# PAYMEE
# PAYMEE
#paymee.base-url=https://sandbox.paymee.tn/api/v2
#paymee.api-token=${PAYMEE_API_TOKEN:c531dc47e04ad09ef573e87c08e4069323eee679}
#paymee.public-base-url=${APP_PUBLIC_URL:https://lyndsey-sawlike-bret.ngrok-free.dev}
#paymee.url=https://sandbox.paymee.tn/api/v2/payments/create
#paymee.token=${PAYMEE_API_TOKEN:c531dc47e04ad09ef573e87c08e4069323eee679}
#paymee.return-url=http://saas-platform:8081/api/payment/redirect-success
#paymee.cancel-url=http://saas-platform:8081/api/payment/redirect-cancel
#paymee.webhook-url=${APP_PUBLIC_URL:https://lyndsey-sawlike-bret.ngrok-free.dev}/api/payment/webhook

# PAYMEE
paymee.base-url=https://sandbox.paymee.tn/api/v2
paymee.api-token=${PAYMEE_API_TOKEN:c531dc47e04ad09ef573e87c08e4069323eee679}

paymee.public-base-url=${APP_PUBLIC_URL}

paymee.return-url=${paymee.public-base-url}/api/payment/redirect-success
paymee.cancel-url=${paymee.public-base-url}/api/payment/redirect-cancel
paymee.webhook-url=${paymee.public-base-url}/api/payment/webhook

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=islemjridi19@gmail.com
spring.mail.password=eyap ggou vpnq xicr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.datasource.driver-class-name=org.postgresql.Driver
# Secret partage entre saas-platform et le pipeline Argo (header X-Internal-Secret)
app.internal.secret=${APP_INTERNAL_SECRET:}
app.platform.url=http://localhost:8081
