# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/saasPlatform
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
app.datasource.demo.url=jdbc:postgresql://localhost:5432/artisdb_demo
app.datasource.demo.username=${DB_USERNAME:postgres}
app.datasource.demo.password=${DB_PASSWORD:postgres}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.enabled=false

# KEYCLOAK
app.keycloak.url=${KEYCLOAK_URL:http://localhost:8080}
keycloak.server-url=${KEYCLOAK_URL:http://localhost:8080}
keycloak.admin-realm=master
keycloak.client-id=${KEYCLOAK_CLIENT_ID:artis-provisioner}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:6eTbohNKVKwn6nfjK1qwExs6HZAzLmmx}
keycloak.admin.username=admin
keycloak.admin.password=admin

# RABBITMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# URLS
app.frontend.url=${FRONTEND_URL:http://localhost:4200}
app.metier.url=http://localhost:4201

# CORS
app.cors.allowed-origins=${FRONTEND_URL:http://localhost:4200},http://localhost:4201

# PAYMEE
# PAYMEE
paymee.base-url=https://sandbox.paymee.tn/api/v2
paymee.api-token=${PAYMEE_API_TOKEN:c531dc47e04ad09ef573e87c08e4069323eee679}
paymee.public-base-url=${APP_PUBLIC_URL:https://lyndsey-sawlike-bret.ngrok-free.dev}
paymee.url=https://sandbox.paymee.tn/api/v2/payments/create
paymee.token=${PAYMEE_API_TOKEN:c531dc47e04ad09ef573e87c08e4069323eee679}
paymee.return-url=${APP_PUBLIC_URL:http://localhost:8081}/api/payment/redirect-success
paymee.cancel-url=${APP_PUBLIC_URL:http://localhost:8081}/api/payment/redirect-cancel
paymee.webhook-url=${APP_PUBLIC_URL:https://lyndsey-sawlike-bret.ngrok-free.dev}/api/payment/webhook

spring.datasource.driver-class-name=org.postgresql.Driver

app.platform.url=http://localhost:8081