# ????????????????????????????
# DATABASE
# ????????????????????????????
spring.datasource.url=jdbc:postgresql://postgresql:5432/saasPlatform
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:postgres}

# Demo database
app.datasource.demo.url=jdbc:postgresql://postgresql:5432/artisdb_demo
app.datasource.demo.username=postgres
app.datasource.demo.password=${DB_PASSWORD:postgres}

# ????????????????????????????
# JPA
# ????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.enabled=false

# ????????????????????????????
# KEYCLOAK
# ????????????????????????????
app.keycloak.url=http://keycloak:8080
keycloak.admin.username=admin
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:admin}

# ????????????????????????????
# RABBITMQ
# ????????????????????????????
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# ????????????????????????????
# URLS
# ????????????????????????????
app.platform.url=http://saas-platform:8081
app.frontend.url=http://angular-platform:80
app.metier.url=http://angular-metier:80

# ????????????????????????????
# CORS
# ????????????????????????????
app.cors.allowed-origins=http://angular-platform:80,http://angular-metier:80,http://localhost:4200,http://localhost:4201

# ????????????????????????????
# PAYMEE
# ????????????????????????????
paymee.url=https://sandbox.paymee.tn/api/v2/payments/create
paymee.token=TON_TOKEN_PAYMEE
paymee.return-url=http://saas-platform:8081/api/payment/redirect-success
paymee.cancel-url=http://saas-platform:8081/api/payment/redirect-cancel
paymee.webhook-url=https://TON_NGROK.ngrok.io/api/payment/webhook

# ????????????????????????????
# MAIL
# ????????????????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=islemjridi19@gmail.com
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true