apiVersion: v1
kind: Secret
metadata:
  name: artis-secrets
  namespace: artis
type: Opaque
stringData:
  postgres-password: "postgres"
  postgres-user: "postgres"
  keycloak-admin-username: "admin"
  keycloak-admin-password: "admin"
  rabbitmq-user: "guest"
  rabbitmq-password: "guest"
  mail-password: "eyap ggou vpnq xicr"
  paymee-api-token: "c531dc47e04ad09ef573e87c08e4069323eee679"