apiVersion: v1
kind: ConfigMap
metadata:
  name: atlas-migrations
  namespace: argo
data:
  schema.hcl: |
    schema "demo" {}

    table "article_groupe" {
      schema = schema.demo
      column "id_groupe_article" {
        null = false
        type = bigint
      }
      column "code_groupe_article" {
        null = true
        type = character_varying(255)
      }
      column "libelle" {
        null = true
        type = character_varying(255)
      }
      column "created_at" {
        null = true
        type = timestamp
      }
      column "updated_at" {
        null = true
        type = timestamp
      }
      primary_key {
        columns = [column.id_groupe_article]
      }
    }

    table "article_categorie" {
      schema = schema.demo
      column "id_categorie_article" {
        null = false
        type = bigint
      }
      column "code_categorie" {
        null = true
        type = character_varying(255)
      }
      column "libelle" {
        null = true
        type = character_varying(255)
      }
      column "fk_groupe_article" {
        null = true
        type = bigint
      }
      column "created_at" {
        null = true
        type = timestamp
      }
      column "updated_at" {
        null = true
        type = timestamp
      }
      primary_key {
        columns = [column.id_categorie_article]
      }
      foreign_key "fk_groupe" {
        columns     = [column.fk_groupe_article]
        ref_columns = [table.article_groupe.column.id_groupe_article]
      }
    }
