-- =============================================
-- SCHEMA COMPLET ARTIS — v3
-- =============================================

-- ─────────────────────────────────────────────
-- GROUPE ARTICLE
-- ─────────────────────────────────────────────
CREATE TABLE article_groupe
(
    id_groupe_article   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code_groupe_article VARCHAR(255),
    libelle             VARCHAR(255),
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_article_groupe PRIMARY KEY (id_groupe_article)
);

ALTER TABLE article_groupe
    ADD CONSTRAINT uc_article_groupe_codegroupearticle UNIQUE (code_groupe_article);

-- ─────────────────────────────────────────────
-- CATEGORIE ARTICLE
-- ─────────────────────────────────────────────
CREATE TABLE article_categorie
(
    id_categorie_article BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code_categorie       VARCHAR(255),
    libelle              VARCHAR(255),
    fk_groupe_article    BIGINT,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_article_categorie PRIMARY KEY (id_categorie_article)
);

ALTER TABLE article_categorie
    ADD CONSTRAINT FK_GROUPE_ARTICLE
        FOREIGN KEY (fk_groupe_article)
            REFERENCES article_groupe (id_groupe_article);

-- ─────────────────────────────────────────────
-- UNITE
-- ─────────────────────────────────────────────
CREATE TABLE article_unite
(
    id_unite   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code_unite VARCHAR(255),
    libelle    VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_article_unite PRIMARY KEY (id_unite)
);

ALTER TABLE article_unite
    ADD CONSTRAINT uc_article_unite_code UNIQUE (code_unite);

-- ─────────────────────────────────────────────
-- ARTICLE
-- ─────────────────────────────────────────────
CREATE TABLE article
(
    id_article           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code_article         VARCHAR(255),
    libelle              VARCHAR(255),
    description          TEXT,
    code_barre           VARCHAR(255),
    prix_achat           NUMERIC(15, 3),
    prix_vente           NUMERIC(15, 3),
    tva                  NUMERIC(5, 2),
    image_url            VARCHAR(255),
    fk_categorie_article BIGINT,
    fk_unite             BIGINT,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_article PRIMARY KEY (id_article)
);

ALTER TABLE article
    ADD CONSTRAINT uc_article_code UNIQUE (code_article);

ALTER TABLE article
    ADD CONSTRAINT fk_categorie_article
        FOREIGN KEY (fk_categorie_article)
            REFERENCES article_categorie (id_categorie_article);

ALTER TABLE article
    ADD CONSTRAINT fk_unite
        FOREIGN KEY (fk_unite)
            REFERENCES article_unite (id_unite);

-- ─────────────────────────────────────────────
-- CLIENT
-- ─────────────────────────────────────────────
CREATE TABLE client
(
    id_client  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom        VARCHAR(255),
    prenom     VARCHAR(255),
    telephone  VARCHAR(50),
    email      VARCHAR(255),
    adresse    TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_client PRIMARY KEY (id_client)
);

-- ─────────────────────────────────────────────
-- COMMANDE
-- ─────────────────────────────────────────────
CREATE TABLE commande
(
    id_commande      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    numero_commande  VARCHAR(255),
    date_commande    DATE,
    fk_client        BIGINT,
    montant_total    NUMERIC(15, 3),
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_commande PRIMARY KEY (id_commande)
);

ALTER TABLE commande
    ADD CONSTRAINT uc_commande_numero UNIQUE (numero_commande);

ALTER TABLE commande
    ADD CONSTRAINT fk_client_commande
        FOREIGN KEY (fk_client)
            REFERENCES client (id_client);

-- ─────────────────────────────────────────────
-- LIGNE COMMANDE
-- ─────────────────────────────────────────────
CREATE TABLE ligne_commande
(
    id_ligne_commande BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fk_commande       BIGINT,
    fk_article        BIGINT,
    quantite          NUMERIC(15, 3),
    prix_unitaire     NUMERIC(15, 3),
    montant_ligne     NUMERIC(15, 3),
    CONSTRAINT pk_ligne_commande PRIMARY KEY (id_ligne_commande)
);

ALTER TABLE ligne_commande
    ADD CONSTRAINT fk_commande_ligne
        FOREIGN KEY (fk_commande)
            REFERENCES commande (id_commande);

ALTER TABLE ligne_commande
    ADD CONSTRAINT fk_article_ligne
        FOREIGN KEY (fk_article)
            REFERENCES article (id_article);